# Generated by Django 5.0.6 on 2024-08-02 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_remove_address_flat_house_no_address_flat_house_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='country',
        ),
        migrations.AddField(
            model_name='address',
            name='fullname',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='address',
            name='mobile',
            field=models.CharField(default='Unknown', max_length=20),
        ),
    ]
