# Generated by Django 5.0.6 on 2024-08-03 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('monitor', 'Monitor'), ('keyboard', 'Keyboard'), ('mouse', 'Mouse'), ('assembled_cpu', 'Assembled CPU'), ('accessory', 'Accessory')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stockLevel', models.PositiveIntegerField()),
                ('description', models.TextField()),
            ],
        ),
    ]
