# Generated by Django 4.2.1 on 2024-08-07 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0009_component_image_alter_component_stocklevel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPC',
            fields=[
                ('configId', models.AutoField(primary_key=True, serialize=False)),
                ('totalPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomPCComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.component')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.custompc')),
            ],
            options={
                'unique_together': {('config', 'component')},
            },
        ),
    ]
