# Generated by Django 4.2.1 on 2024-08-24 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0018_alter_rating_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='updated_at',
        ),
    ]
