# Generated by Django 4.2.1 on 2024-08-31 10:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0021_alter_rating_description_alter_rating_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='custompc',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='custompc',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
