# Generated by Django 4.2.1 on 2024-09-01 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0023_rename_totalprice_custompc_total_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custompc',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
