# Generated by Django 4.2.1 on 2024-09-05 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0028_custompcmessage_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='custompcmessage',
            name='is_from_user',
            field=models.BooleanField(default=False),
        ),
    ]
