# Generated by Django 4.2.1 on 2024-09-05 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0029_custompcmessage_is_from_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custompccomponent',
            name='component',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='userapp.component'),
        ),
    ]
