# Generated by Django 4.2.1 on 2024-10-16 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0034_custompcorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='custompcorder',
            old_name='order_date',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='custompc',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='custompcorder',
            name='bluetooth_card',
        ),
        migrations.RemoveField(
            model_name='custompcorder',
            name='case',
        ),
        migrations.RemoveField(
            model_name='custompcorder',
            name='cpu',
        ),
        migrations.RemoveField(
            model_name='custompcorder',
            name='gpu',
        ),
        migrations.RemoveField(
            model_name='custompcorder',
            name='motherboard',
        ),
        migrations.RemoveField(
            model_name='custompcorder',
            name='power_supply',
        ),
        migrations.RemoveField(
            model_name='custompcorder',
            name='ram',
        ),
        migrations.RemoveField(
            model_name='custompcorder',
            name='storage',
        ),
        migrations.RemoveField(
            model_name='custompcorder',
            name='wifi_card',
        ),
        migrations.AddField(
            model_name='custompcorder',
            name='status',
            field=models.CharField(default='paid', max_length=20),
        ),
        migrations.CreateModel(
            name='OrderComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_name', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='userapp.custompcorder')),
            ],
        ),
    ]
