# Generated by Django 4.2.1 on 2024-10-17 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0036_custompc_total_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custompc',
            name='total_price',
        ),
        migrations.AlterField(
            model_name='custompccomponent',
            name='custom_pc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.custompc'),
        ),
    ]
