# Generated by Django 4.2.1 on 2024-10-17 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0037_remove_custompc_total_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='custompcorder',
            name='build',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='userapp.custompc'),
            preserve_default=False,
        ),
    ]
