# Generated by Django 4.2.1 on 2024-10-17 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0038_custompcorder_build'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='custompccomponent',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='custompc',
            name='status',
        ),
        migrations.AddField(
            model_name='custompc',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='custompc',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=9, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='custompccomponent',
            name='component',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='userapp.component'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='custompccomponent',
            name='custom_pc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='userapp.custompc'),
        ),
        migrations.AlterField(
            model_name='custompccomponent',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.RemoveField(
            model_name='custompccomponent',
            name='recommendedcomponent',
        ),
    ]
