# Generated by Django 4.2.1 on 2024-10-17 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0039_alter_custompccomponent_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='custompc',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
