# Generated by Django 4.2.1 on 2024-10-17 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0040_custompc_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='custompccomponent',
            name='recommendedcomponent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='custompccomponent',
            unique_together={('custom_pc', 'component')},
        ),
    ]
