# Generated by Django 4.2.1 on 2024-10-25 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0041_custompccomponent_recommendedcomponent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custompcorder',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('building', 'Building'), ('shipped', 'Shipped'), ('enroute', 'En Route'), ('arrived', 'Arrived')], default='paid', max_length=20),
        ),
    ]
