# Generated by Django 4.2.1 on 2024-10-25 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0042_alter_custompcorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custompcorder',
            name='status',
            field=models.CharField(choices=[('rejected', 'Rejected'), ('pending', 'Pending'), ('paid', 'Paid'), ('building', 'Building'), ('shipped', 'Shipped'), ('enroute', 'En Route'), ('arrived', 'Arrived')], default='pending', max_length=20),
        ),
    ]
