# Generated by Django 4.2.1 on 2025-01-27 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0043_alter_custompcorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('staff', 'Staff'), ('admin', 'Admin'), ('delivery_boy', 'Delivery Boy')], default='user', max_length=20),
        ),
    ]
