# Generated by Django 4.2.1 on 2025-01-27 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0044_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_deliveryboy',
            field=models.BooleanField(default=False),
        ),
    ]
