# Generated by Django 4.2.1 on 2025-01-28 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0046_deliveryboy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryboy',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('busy', 'Busy'), ('offline', 'Offline')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='deliveryboy',
            name='vehicle_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
