# Generated by Django 4.2.1 on 2025-01-28 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0047_alter_deliveryboy_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveryboy',
            options={},
        ),
        migrations.AddField(
            model_name='deliveryboy',
            name='address',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='deliveryboy',
            name='district',
            field=models.CharField(blank=True, choices=[('alappuzha', 'Alappuzha'), ('ernakulam', 'Ernakulam'), ('idukki', 'Idukki'), ('kannur', 'Kannur'), ('kasaragod', 'Kasaragod'), ('kollam', 'Kollam'), ('kottayam', 'Kottayam'), ('kozhikode', 'Kozhikode'), ('malappuram', 'Malappuram'), ('palakkad', 'Palakkad'), ('pathanamthitta', 'Pathanamthitta'), ('thiruvananthapuram', 'Thiruvananthapuram'), ('thrissur', 'Thrissur'), ('wayanad', 'Wayanad')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='deliveryboy',
            name='pincode',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
