# Generated by Django 4.2.1 on 2025-01-30 05:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0048_alter_deliveryboy_options_deliveryboy_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('deliveryId', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('dispatched', 'Dispatched'), ('delivered', 'Delivered')], default='pending', max_length=100)),
                ('assignedDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('deliveryDate', models.DateTimeField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('locationTracking', models.CharField(blank=True, max_length=255, null=True)),
                ('deliveryBoyId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='userapp.deliveryboy')),
                ('orderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='userapp.custompcorder')),
            ],
            options={
                'db_table': 'Delivery',
                'ordering': ['-assignedDate'],
            },
        ),
    ]
