# Generated by Django 4.2.1 on 2025-01-30 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0049_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('acceptedassigned', 'Accepted Assignment'), ('onway', 'On The Way'), ('delivered', 'Delivered')], default='assigned', max_length=100),
        ),
    ]
